/*
Copyright 2022 The SODA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/soda-cdm/kahu/apis/kahu/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProviderRegistrations implements ProviderRegistrationInterface
type FakeProviderRegistrations struct {
	Fake *FakeKahuV1beta1
}

var providerregistrationsResource = schema.GroupVersionResource{Group: "kahu.io", Version: "v1beta1", Resource: "providerregistrations"}

var providerregistrationsKind = schema.GroupVersionKind{Group: "kahu.io", Version: "v1beta1", Kind: "ProviderRegistration"}

// Get takes name of the providerRegistration, and returns the corresponding providerRegistration object, and an error if there is any.
func (c *FakeProviderRegistrations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ProviderRegistration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(providerregistrationsResource, name), &v1beta1.ProviderRegistration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ProviderRegistration), err
}

// List takes label and field selectors, and returns the list of ProviderRegistrations that match those selectors.
func (c *FakeProviderRegistrations) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ProviderRegistrationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(providerregistrationsResource, providerregistrationsKind, opts), &v1beta1.ProviderRegistrationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ProviderRegistrationList{ListMeta: obj.(*v1beta1.ProviderRegistrationList).ListMeta}
	for _, item := range obj.(*v1beta1.ProviderRegistrationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested providerRegistrations.
func (c *FakeProviderRegistrations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(providerregistrationsResource, opts))
}

// Create takes the representation of a providerRegistration and creates it.  Returns the server's representation of the providerRegistration, and an error, if there is any.
func (c *FakeProviderRegistrations) Create(ctx context.Context, providerRegistration *v1beta1.ProviderRegistration, opts v1.CreateOptions) (result *v1beta1.ProviderRegistration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(providerregistrationsResource, providerRegistration), &v1beta1.ProviderRegistration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ProviderRegistration), err
}

// Update takes the representation of a providerRegistration and updates it. Returns the server's representation of the providerRegistration, and an error, if there is any.
func (c *FakeProviderRegistrations) Update(ctx context.Context, providerRegistration *v1beta1.ProviderRegistration, opts v1.UpdateOptions) (result *v1beta1.ProviderRegistration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(providerregistrationsResource, providerRegistration), &v1beta1.ProviderRegistration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ProviderRegistration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProviderRegistrations) UpdateStatus(ctx context.Context, providerRegistration *v1beta1.ProviderRegistration, opts v1.UpdateOptions) (*v1beta1.ProviderRegistration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(providerregistrationsResource, "status", providerRegistration), &v1beta1.ProviderRegistration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ProviderRegistration), err
}

// Delete takes name of the providerRegistration and deletes it. Returns an error if one occurs.
func (c *FakeProviderRegistrations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(providerregistrationsResource, name), &v1beta1.ProviderRegistration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProviderRegistrations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(providerregistrationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ProviderRegistrationList{})
	return err
}

// Patch applies the patch and returns the patched providerRegistration.
func (c *FakeProviderRegistrations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ProviderRegistration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(providerregistrationsResource, name, pt, data, subresources...), &v1beta1.ProviderRegistration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ProviderRegistration), err
}
