/*
Copyright 2022 The SODA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/soda-cdm/kahu/apis/kahu/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolumeRestoreContents implements VolumeRestoreContentInterface
type FakeVolumeRestoreContents struct {
	Fake *FakeKahuV1beta1
}

var volumerestorecontentsResource = schema.GroupVersionResource{Group: "kahu.io", Version: "v1beta1", Resource: "volumerestorecontents"}

var volumerestorecontentsKind = schema.GroupVersionKind{Group: "kahu.io", Version: "v1beta1", Kind: "VolumeRestoreContent"}

// Get takes name of the volumeRestoreContent, and returns the corresponding volumeRestoreContent object, and an error if there is any.
func (c *FakeVolumeRestoreContents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.VolumeRestoreContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(volumerestorecontentsResource, name), &v1beta1.VolumeRestoreContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VolumeRestoreContent), err
}

// List takes label and field selectors, and returns the list of VolumeRestoreContents that match those selectors.
func (c *FakeVolumeRestoreContents) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.VolumeRestoreContentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(volumerestorecontentsResource, volumerestorecontentsKind, opts), &v1beta1.VolumeRestoreContentList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.VolumeRestoreContentList{ListMeta: obj.(*v1beta1.VolumeRestoreContentList).ListMeta}
	for _, item := range obj.(*v1beta1.VolumeRestoreContentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volumeRestoreContents.
func (c *FakeVolumeRestoreContents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(volumerestorecontentsResource, opts))
}

// Create takes the representation of a volumeRestoreContent and creates it.  Returns the server's representation of the volumeRestoreContent, and an error, if there is any.
func (c *FakeVolumeRestoreContents) Create(ctx context.Context, volumeRestoreContent *v1beta1.VolumeRestoreContent, opts v1.CreateOptions) (result *v1beta1.VolumeRestoreContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(volumerestorecontentsResource, volumeRestoreContent), &v1beta1.VolumeRestoreContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VolumeRestoreContent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVolumeRestoreContents) UpdateStatus(ctx context.Context, volumeRestoreContent *v1beta1.VolumeRestoreContent, opts v1.UpdateOptions) (*v1beta1.VolumeRestoreContent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(volumerestorecontentsResource, "status", volumeRestoreContent), &v1beta1.VolumeRestoreContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VolumeRestoreContent), err
}

// Delete takes name of the volumeRestoreContent and deletes it. Returns an error if one occurs.
func (c *FakeVolumeRestoreContents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(volumerestorecontentsResource, name), &v1beta1.VolumeRestoreContent{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolumeRestoreContents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(volumerestorecontentsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.VolumeRestoreContentList{})
	return err
}

// Patch applies the patch and returns the patched volumeRestoreContent.
func (c *FakeVolumeRestoreContents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VolumeRestoreContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(volumerestorecontentsResource, name, pt, data, subresources...), &v1beta1.VolumeRestoreContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.VolumeRestoreContent), err
}
