// Code generated by make; DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.1
// source: proto/metaservice.proto

package metaservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*BackupRequest_Backup
	//	*BackupRequest_Object_
	Data isBackupRequest_Data `protobuf_oneof:"Data"`
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metaservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metaservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_metaservice_proto_rawDescGZIP(), []int{0}
}

func (m *BackupRequest) GetData() isBackupRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *BackupRequest) GetBackup() *BackupRequest_BackupIdentifier {
	if x, ok := x.GetData().(*BackupRequest_Backup); ok {
		return x.Backup
	}
	return nil
}

func (x *BackupRequest) GetObject() *BackupRequest_Object {
	if x, ok := x.GetData().(*BackupRequest_Object_); ok {
		return x.Object
	}
	return nil
}

type isBackupRequest_Data interface {
	isBackupRequest_Data()
}

type BackupRequest_Backup struct {
	Backup *BackupRequest_BackupIdentifier `protobuf:"bytes,1,opt,name=backup,proto3,oneof"`
}

type BackupRequest_Object_ struct {
	Object *BackupRequest_Object `protobuf:"bytes,2,opt,name=object,proto3,oneof"`
}

func (*BackupRequest_Backup) isBackupRequest_Data() {}

func (*BackupRequest_Object_) isBackupRequest_Data() {}

type RestoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackupHandle  string            `protobuf:"bytes,1,opt,name=backup_handle,json=backupHandle,proto3" json:"backup_handle,omitempty"`
	BackupLoction string            `protobuf:"bytes,2,opt,name=backup_loction,json=backupLoction,proto3" json:"backup_loction,omitempty"`
	Parameters    map[string]string `protobuf:"bytes,9,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metaservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metaservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_metaservice_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreRequest) GetBackupHandle() string {
	if x != nil {
		return x.BackupHandle
	}
	return ""
}

func (x *RestoreRequest) GetBackupLoction() string {
	if x != nil {
		return x.BackupLoction
	}
	return ""
}

func (x *RestoreRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueIdentification string `protobuf:"bytes,1,opt,name=unique_identification,json=uniqueIdentification,proto3" json:"unique_identification,omitempty"`
	Object               string `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metaservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metaservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_metaservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetUniqueIdentification() string {
	if x != nil {
		return x.UniqueIdentification
	}
	return ""
}

func (x *GetResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metaservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metaservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_metaservice_proto_rawDescGZIP(), []int{3}
}

type BackupRequest_BackupIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackupHandle  string            `protobuf:"bytes,1,opt,name=backup_handle,json=backupHandle,proto3" json:"backup_handle,omitempty"`
	BackupLoction string            `protobuf:"bytes,2,opt,name=backup_loction,json=backupLoction,proto3" json:"backup_loction,omitempty"`
	Parameters    map[string]string `protobuf:"bytes,9,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BackupRequest_BackupIdentifier) Reset() {
	*x = BackupRequest_BackupIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metaservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupRequest_BackupIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest_BackupIdentifier) ProtoMessage() {}

func (x *BackupRequest_BackupIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metaservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest_BackupIdentifier.ProtoReflect.Descriptor instead.
func (*BackupRequest_BackupIdentifier) Descriptor() ([]byte, []int) {
	return file_proto_metaservice_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BackupRequest_BackupIdentifier) GetBackupHandle() string {
	if x != nil {
		return x.BackupHandle
	}
	return ""
}

func (x *BackupRequest_BackupIdentifier) GetBackupLoction() string {
	if x != nil {
		return x.BackupLoction
	}
	return ""
}

func (x *BackupRequest_BackupIdentifier) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type BackupRequest_Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueIdentification string `protobuf:"bytes,1,opt,name=unique_identification,json=uniqueIdentification,proto3" json:"unique_identification,omitempty"`
	Json                 string `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *BackupRequest_Object) Reset() {
	*x = BackupRequest_Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_metaservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupRequest_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest_Object) ProtoMessage() {}

func (x *BackupRequest_Object) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metaservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest_Object.ProtoReflect.Descriptor instead.
func (*BackupRequest_Object) Descriptor() ([]byte, []int) {
	return file_proto_metaservice_proto_rawDescGZIP(), []int{0, 1}
}

func (x *BackupRequest_Object) GetUniqueIdentification() string {
	if x != nil {
		return x.UniqueIdentification
	}
	return ""
}

func (x *BackupRequest_Object) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_proto_metaservice_proto protoreflect.FileDescriptor

var file_proto_metaservice_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6b, 0x61, 0x68, 0x75, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xfa, 0x03, 0x0a, 0x0d,
	0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4a, 0x0a,
	0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x6b, 0x61, 0x68, 0x75, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x06, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x40, 0x0a, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6b, 0x61, 0x68, 0x75,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0xff, 0x01, 0x0a, 0x10,
	0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x12, 0x23, 0x0a, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f,
	0x6c, 0x6f, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x60, 0x0a, 0x0a,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x40, 0x2e, 0x6b, 0x61, 0x68, 0x75, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x3d,
	0x0a, 0x0f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x51, 0x0a,
	0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x33, 0x0a, 0x15, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e,
	0x42, 0x06, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0xed, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x62,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x6c, 0x6f, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x4c, 0x6f, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x50, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6b, 0x61,
	0x68, 0x75, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x15, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xa5, 0x01,
	0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a,
	0x06, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x1f, 0x2e, 0x6b, 0x61, 0x68, 0x75, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6b, 0x61, 0x68, 0x75, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x28, 0x01, 0x12, 0x4e, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x12, 0x20, 0x2e, 0x6b, 0x61, 0x68, 0x75, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6b, 0x61, 0x68, 0x75, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x6c, 0x69, 0x62, 0x2f, 0x67, 0x6f, 0x3b,
	0x6d, 0x65, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_metaservice_proto_rawDescOnce sync.Once
	file_proto_metaservice_proto_rawDescData = file_proto_metaservice_proto_rawDesc
)

func file_proto_metaservice_proto_rawDescGZIP() []byte {
	file_proto_metaservice_proto_rawDescOnce.Do(func() {
		file_proto_metaservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_metaservice_proto_rawDescData)
	})
	return file_proto_metaservice_proto_rawDescData
}

var file_proto_metaservice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_metaservice_proto_goTypes = []interface{}{
	(*BackupRequest)(nil),                  // 0: kahu.metaservice.BackupRequest
	(*RestoreRequest)(nil),                 // 1: kahu.metaservice.RestoreRequest
	(*GetResponse)(nil),                    // 2: kahu.metaservice.GetResponse
	(*Empty)(nil),                          // 3: kahu.metaservice.Empty
	(*BackupRequest_BackupIdentifier)(nil), // 4: kahu.metaservice.BackupRequest.BackupIdentifier
	(*BackupRequest_Object)(nil),           // 5: kahu.metaservice.BackupRequest.Object
	nil,                                    // 6: kahu.metaservice.BackupRequest.BackupIdentifier.ParametersEntry
	nil,                                    // 7: kahu.metaservice.RestoreRequest.ParametersEntry
}
var file_proto_metaservice_proto_depIdxs = []int32{
	4, // 0: kahu.metaservice.BackupRequest.backup:type_name -> kahu.metaservice.BackupRequest.BackupIdentifier
	5, // 1: kahu.metaservice.BackupRequest.object:type_name -> kahu.metaservice.BackupRequest.Object
	7, // 2: kahu.metaservice.RestoreRequest.parameters:type_name -> kahu.metaservice.RestoreRequest.ParametersEntry
	6, // 3: kahu.metaservice.BackupRequest.BackupIdentifier.parameters:type_name -> kahu.metaservice.BackupRequest.BackupIdentifier.ParametersEntry
	0, // 4: kahu.metaservice.MetaService.Backup:input_type -> kahu.metaservice.BackupRequest
	1, // 5: kahu.metaservice.MetaService.Restore:input_type -> kahu.metaservice.RestoreRequest
	3, // 6: kahu.metaservice.MetaService.Backup:output_type -> kahu.metaservice.Empty
	2, // 7: kahu.metaservice.MetaService.Restore:output_type -> kahu.metaservice.GetResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_metaservice_proto_init() }
func file_proto_metaservice_proto_init() {
	if File_proto_metaservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_metaservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metaservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metaservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metaservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metaservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupRequest_BackupIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_metaservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupRequest_Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_metaservice_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BackupRequest_Backup)(nil),
		(*BackupRequest_Object_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_metaservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metaservice_proto_goTypes,
		DependencyIndexes: file_proto_metaservice_proto_depIdxs,
		MessageInfos:      file_proto_metaservice_proto_msgTypes,
	}.Build()
	File_proto_metaservice_proto = out.File
	file_proto_metaservice_proto_rawDesc = nil
	file_proto_metaservice_proto_goTypes = nil
	file_proto_metaservice_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MetaServiceClient is the client API for MetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaServiceClient interface {
	Backup(ctx context.Context, opts ...grpc.CallOption) (MetaService_BackupClient, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (MetaService_RestoreClient, error)
}

type metaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaServiceClient(cc grpc.ClientConnInterface) MetaServiceClient {
	return &metaServiceClient{cc}
}

func (c *metaServiceClient) Backup(ctx context.Context, opts ...grpc.CallOption) (MetaService_BackupClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MetaService_serviceDesc.Streams[0], "/kahu.metaservice.MetaService/Backup", opts...)
	if err != nil {
		return nil, err
	}
	x := &metaServiceBackupClient{stream}
	return x, nil
}

type MetaService_BackupClient interface {
	Send(*BackupRequest) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type metaServiceBackupClient struct {
	grpc.ClientStream
}

func (x *metaServiceBackupClient) Send(m *BackupRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metaServiceBackupClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metaServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (MetaService_RestoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MetaService_serviceDesc.Streams[1], "/kahu.metaservice.MetaService/Restore", opts...)
	if err != nil {
		return nil, err
	}
	x := &metaServiceRestoreClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MetaService_RestoreClient interface {
	Recv() (*GetResponse, error)
	grpc.ClientStream
}

type metaServiceRestoreClient struct {
	grpc.ClientStream
}

func (x *metaServiceRestoreClient) Recv() (*GetResponse, error) {
	m := new(GetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MetaServiceServer is the server API for MetaService service.
type MetaServiceServer interface {
	Backup(MetaService_BackupServer) error
	Restore(*RestoreRequest, MetaService_RestoreServer) error
}

// UnimplementedMetaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetaServiceServer struct {
}

func (*UnimplementedMetaServiceServer) Backup(MetaService_BackupServer) error {
	return status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (*UnimplementedMetaServiceServer) Restore(*RestoreRequest, MetaService_RestoreServer) error {
	return status.Errorf(codes.Unimplemented, "method Restore not implemented")
}

func RegisterMetaServiceServer(s *grpc.Server, srv MetaServiceServer) {
	s.RegisterService(&_MetaService_serviceDesc, srv)
}

func _MetaService_Backup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetaServiceServer).Backup(&metaServiceBackupServer{stream})
}

type MetaService_BackupServer interface {
	SendAndClose(*Empty) error
	Recv() (*BackupRequest, error)
	grpc.ServerStream
}

type metaServiceBackupServer struct {
	grpc.ServerStream
}

func (x *metaServiceBackupServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metaServiceBackupServer) Recv() (*BackupRequest, error) {
	m := new(BackupRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MetaService_Restore_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RestoreRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetaServiceServer).Restore(m, &metaServiceRestoreServer{stream})
}

type MetaService_RestoreServer interface {
	Send(*GetResponse) error
	grpc.ServerStream
}

type metaServiceRestoreServer struct {
	grpc.ServerStream
}

func (x *metaServiceRestoreServer) Send(m *GetResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MetaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kahu.metaservice.MetaService",
	HandlerType: (*MetaServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Backup",
			Handler:       _MetaService_Backup_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Restore",
			Handler:       _MetaService_Restore_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/metaservice.proto",
}
