// Copyright 2022 The SODA Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	kahuv1beta1 "github.com/soda-cdm/kahu/apis/kahu/v1beta1"
	versioned "github.com/soda-cdm/kahu/client/clientset/versioned"
	internalinterfaces "github.com/soda-cdm/kahu/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/soda-cdm/kahu/client/listers/kahu/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ProviderInformer provides access to a shared informer and lister for
// Providers.
type ProviderInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ProviderLister
}

type providerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewProviderInformer constructs a new informer for Provider type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewProviderInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredProviderInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredProviderInformer constructs a new informer for Provider type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredProviderInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KahuV1beta1().Providers().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KahuV1beta1().Providers().Watch(context.TODO(), options)
			},
		},
		&kahuv1beta1.Provider{},
		resyncPeriod,
		indexers,
	)
}

func (f *providerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredProviderInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *providerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kahuv1beta1.Provider{}, f.defaultInformer)
}

func (f *providerInformer) Lister() v1beta1.ProviderLister {
	return v1beta1.NewProviderLister(f.Informer().GetIndexer())
}
