/*
Copyright 2022 The SODA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/soda-cdm/kahu/apis/kahu/v1beta1"
	scheme "github.com/soda-cdm/kahu/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ProviderRegistrationsGetter has a method to return a ProviderRegistrationInterface.
// A group's client should implement this interface.
type ProviderRegistrationsGetter interface {
	ProviderRegistrations() ProviderRegistrationInterface
}

// ProviderRegistrationInterface has methods to work with ProviderRegistration resources.
type ProviderRegistrationInterface interface {
	Create(ctx context.Context, providerRegistration *v1beta1.ProviderRegistration, opts v1.CreateOptions) (*v1beta1.ProviderRegistration, error)
	Update(ctx context.Context, providerRegistration *v1beta1.ProviderRegistration, opts v1.UpdateOptions) (*v1beta1.ProviderRegistration, error)
	UpdateStatus(ctx context.Context, providerRegistration *v1beta1.ProviderRegistration, opts v1.UpdateOptions) (*v1beta1.ProviderRegistration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ProviderRegistration, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ProviderRegistrationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ProviderRegistration, err error)
	ProviderRegistrationExpansion
}

// providerRegistrations implements ProviderRegistrationInterface
type providerRegistrations struct {
	client rest.Interface
}

// newProviderRegistrations returns a ProviderRegistrations
func newProviderRegistrations(c *KahuV1beta1Client) *providerRegistrations {
	return &providerRegistrations{
		client: c.RESTClient(),
	}
}

// Get takes name of the providerRegistration, and returns the corresponding providerRegistration object, and an error if there is any.
func (c *providerRegistrations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ProviderRegistration, err error) {
	result = &v1beta1.ProviderRegistration{}
	err = c.client.Get().
		Resource("providerregistrations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ProviderRegistrations that match those selectors.
func (c *providerRegistrations) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ProviderRegistrationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ProviderRegistrationList{}
	err = c.client.Get().
		Resource("providerregistrations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested providerRegistrations.
func (c *providerRegistrations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("providerregistrations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a providerRegistration and creates it.  Returns the server's representation of the providerRegistration, and an error, if there is any.
func (c *providerRegistrations) Create(ctx context.Context, providerRegistration *v1beta1.ProviderRegistration, opts v1.CreateOptions) (result *v1beta1.ProviderRegistration, err error) {
	result = &v1beta1.ProviderRegistration{}
	err = c.client.Post().
		Resource("providerregistrations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(providerRegistration).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a providerRegistration and updates it. Returns the server's representation of the providerRegistration, and an error, if there is any.
func (c *providerRegistrations) Update(ctx context.Context, providerRegistration *v1beta1.ProviderRegistration, opts v1.UpdateOptions) (result *v1beta1.ProviderRegistration, err error) {
	result = &v1beta1.ProviderRegistration{}
	err = c.client.Put().
		Resource("providerregistrations").
		Name(providerRegistration.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(providerRegistration).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *providerRegistrations) UpdateStatus(ctx context.Context, providerRegistration *v1beta1.ProviderRegistration, opts v1.UpdateOptions) (result *v1beta1.ProviderRegistration, err error) {
	result = &v1beta1.ProviderRegistration{}
	err = c.client.Put().
		Resource("providerregistrations").
		Name(providerRegistration.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(providerRegistration).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the providerRegistration and deletes it. Returns an error if one occurs.
func (c *providerRegistrations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("providerregistrations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *providerRegistrations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("providerregistrations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched providerRegistration.
func (c *providerRegistrations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ProviderRegistration, err error) {
	result = &v1beta1.ProviderRegistration{}
	err = c.client.Patch(pt).
		Resource("providerregistrations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
