/*
Copyright 2022 The SODA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/soda-cdm/kahu/apis/kahu/v1beta1"
	scheme "github.com/soda-cdm/kahu/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VolumeGroupsGetter has a method to return a VolumeGroupInterface.
// A group's client should implement this interface.
type VolumeGroupsGetter interface {
	VolumeGroups() VolumeGroupInterface
}

// VolumeGroupInterface has methods to work with VolumeGroup resources.
type VolumeGroupInterface interface {
	Create(ctx context.Context, volumeGroup *v1beta1.VolumeGroup, opts v1.CreateOptions) (*v1beta1.VolumeGroup, error)
	Update(ctx context.Context, volumeGroup *v1beta1.VolumeGroup, opts v1.UpdateOptions) (*v1beta1.VolumeGroup, error)
	UpdateStatus(ctx context.Context, volumeGroup *v1beta1.VolumeGroup, opts v1.UpdateOptions) (*v1beta1.VolumeGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.VolumeGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.VolumeGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VolumeGroup, err error)
	VolumeGroupExpansion
}

// volumeGroups implements VolumeGroupInterface
type volumeGroups struct {
	client rest.Interface
}

// newVolumeGroups returns a VolumeGroups
func newVolumeGroups(c *KahuV1beta1Client) *volumeGroups {
	return &volumeGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the volumeGroup, and returns the corresponding volumeGroup object, and an error if there is any.
func (c *volumeGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.VolumeGroup, err error) {
	result = &v1beta1.VolumeGroup{}
	err = c.client.Get().
		Resource("volumegroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VolumeGroups that match those selectors.
func (c *volumeGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.VolumeGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.VolumeGroupList{}
	err = c.client.Get().
		Resource("volumegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested volumeGroups.
func (c *volumeGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("volumegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a volumeGroup and creates it.  Returns the server's representation of the volumeGroup, and an error, if there is any.
func (c *volumeGroups) Create(ctx context.Context, volumeGroup *v1beta1.VolumeGroup, opts v1.CreateOptions) (result *v1beta1.VolumeGroup, err error) {
	result = &v1beta1.VolumeGroup{}
	err = c.client.Post().
		Resource("volumegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a volumeGroup and updates it. Returns the server's representation of the volumeGroup, and an error, if there is any.
func (c *volumeGroups) Update(ctx context.Context, volumeGroup *v1beta1.VolumeGroup, opts v1.UpdateOptions) (result *v1beta1.VolumeGroup, err error) {
	result = &v1beta1.VolumeGroup{}
	err = c.client.Put().
		Resource("volumegroups").
		Name(volumeGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeGroup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *volumeGroups) UpdateStatus(ctx context.Context, volumeGroup *v1beta1.VolumeGroup, opts v1.UpdateOptions) (result *v1beta1.VolumeGroup, err error) {
	result = &v1beta1.VolumeGroup{}
	err = c.client.Put().
		Resource("volumegroups").
		Name(volumeGroup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(volumeGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the volumeGroup and deletes it. Returns an error if one occurs.
func (c *volumeGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("volumegroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *volumeGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("volumegroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched volumeGroup.
func (c *volumeGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VolumeGroup, err error) {
	result = &v1beta1.VolumeGroup{}
	err = c.client.Patch(pt).
		Resource("volumegroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
